//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestrIV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektSemestrIV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        public static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Competition.
        /// </summary>
        public static string AddCompetition {
            get {
                return ResourceManager.GetString("AddCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stage.
        /// </summary>
        public static string AddStage {
            get {
                return ResourceManager.GetString("AddStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Accuracy.
        /// </summary>
        public static string AlphaAccuracy {
            get {
                return ResourceManager.GetString("AlphaAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Position.
        /// </summary>
        public static string AveragePosition {
            get {
                return ResourceManager.GetString("AveragePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time.
        /// </summary>
        public static string AverageTime {
            get {
                return ResourceManager.GetString("AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best shooter.
        /// </summary>
        public static string BestShooter {
            get {
                return ResourceManager.GetString("BestShooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string Charlie {
            get {
                return ResourceManager.GetString("Charlie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charlie Accuracy.
        /// </summary>
        public static string CharlieAccuracy {
            get {
                return ResourceManager.GetString("CharlieAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition points.
        /// </summary>
        public static string CompetitionPoints {
            get {
                return ResourceManager.GetString("CompetitionPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitions.
        /// </summary>
        public static string Competitions {
            get {
                return ResourceManager.GetString("Competitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Summary.
        /// </summary>
        public static string CompetitionSummary {
            get {
                return ResourceManager.GetString("CompetitionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Configuration.
        /// </summary>
        public static string ConnectionConfiguration {
            get {
                return ResourceManager.GetString("ConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Delta {
            get {
                return ResourceManager.GetString("Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Accuracy.
        /// </summary>
        public static string DeltaAccuracy {
            get {
                return ResourceManager.GetString("DeltaAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration date.
        /// </summary>
        public static string DurationDate {
            get {
                return ResourceManager.GetString("DurationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Competition.
        /// </summary>
        public static string EditCompetition {
            get {
                return ResourceManager.GetString("EditCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Run.
        /// </summary>
        public static string EditRun {
            get {
                return ResourceManager.GetString("EditRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shooter.
        /// </summary>
        public static string EditShooter {
            get {
                return ResourceManager.GetString("EditShooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stage.
        /// </summary>
        public static string EditStage {
            get {
                return ResourceManager.GetString("EditStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xtra.
        /// </summary>
        public static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest run.
        /// </summary>
        public static string FastestRun {
            get {
                return ResourceManager.GetString("FastestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Accuracy.
        /// </summary>
        public static string GeneralAccuracy {
            get {
                return ResourceManager.GetString("GeneralAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition Id.
        /// </summary>
        public static string IdCompetition {
            get {
                return ResourceManager.GetString("IdCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition List.
        /// </summary>
        public static string ListCompetition {
            get {
                return ResourceManager.GetString("ListCompetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooters List.
        /// </summary>
        public static string ListShooters {
            get {
                return ResourceManager.GetString("ListShooters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages list.
        /// </summary>
        public static string ListStages {
            get {
                return ResourceManager.GetString("ListStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISS.
        /// </summary>
        public static string Miss {
            get {
                return ResourceManager.GetString("Miss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N-S.
        /// </summary>
        public static string NoShoot {
            get {
                return ResourceManager.GetString("NoShoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of participatns.
        /// </summary>
        public static string NumberOfParticipants {
            get {
                return ResourceManager.GetString("NumberOfParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of targets.
        /// </summary>
        public static string NumberOfTargets {
            get {
                return ResourceManager.GetString("NumberOfTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podium.
        /// </summary>
        public static string Podium {
            get {
                return ResourceManager.GetString("Podium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Adress.
        /// </summary>
        public static string ServerAdress {
            get {
                return ResourceManager.GetString("ServerAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter.
        /// </summary>
        public static string Shooter {
            get {
                return ResourceManager.GetString("Shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter Editing.
        /// </summary>
        public static string ShooterEditing {
            get {
                return ResourceManager.GetString("ShooterEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShooterID.
        /// </summary>
        public static string ShooterID {
            get {
                return ResourceManager.GetString("ShooterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ShooterName {
            get {
                return ResourceManager.GetString("ShooterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter on competition summary.
        /// </summary>
        public static string ShooterOnCompetitionSummary {
            get {
                return ResourceManager.GetString("ShooterOnCompetitionSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter on stage summary.
        /// </summary>
        public static string ShooterOnStageSummary {
            get {
                return ResourceManager.GetString("ShooterOnStageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shooter summary.
        /// </summary>
        public static string ShooterSummary {
            get {
                return ResourceManager.GetString("ShooterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string ShooterSurname {
            get {
                return ResourceManager.GetString("ShooterSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StageID.
        /// </summary>
        public static string StageID {
            get {
                return ResourceManager.GetString("StageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage name.
        /// </summary>
        public static string StageName {
            get {
                return ResourceManager.GetString("StageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage points.
        /// </summary>
        public static string StagePoints {
            get {
                return ResourceManager.GetString("StagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage ranking.
        /// </summary>
        public static string StageRanking {
            get {
                return ResourceManager.GetString("StageRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Summary.
        /// </summary>
        public static string StageSummary {
            get {
                return ResourceManager.GetString("StageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of points.
        /// </summary>
        public static string SumOfPoints {
            get {
                return ResourceManager.GetString("SumOfPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of times.
        /// </summary>
        public static string SumOfTimes {
            get {
                return ResourceManager.GetString("SumOfTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
